# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone (đã chỉnh)
timezone: "Asia/Ho_Chi_Minh"

# jekyll-seo-tag settings
title: "Phat's Blog"
tagline: "Pentester/Redteam"
description: >-
  A blog about cybersecurity, hacking, pentesting, red teaming and more.

# Fill in the protocol & hostname for your site.
url: "https://pzhat.github.io"

github:
  username: pzhat

twitter:
  username: pzhat

social:
  name: "Phat Mai"
  email: phast28904@gmail.com
  links:
    - https://twitter.com/pzhat
    - https://github.com/pzhat
    - https://www.facebook.com/phat.mai.79069
    - https://www.linkedin.com/in/phat-mai-hong-2580a52aa/

# Site Verification Settings (để trống nếu chưa có)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings (nhập ID nếu có)
analytics:
  google:
    id: ""       # Ví dụ: G-XXXXXXXXXX
  goatcounter:
    id: ""
  umami:
    id: ""
    domain: ""
  matomo:
    id: ""
    domain: ""
  cloudflare:
    id: ""
  fathom:
    id: ""

# Page views settings
pageviews:
  provider: "" # now only supports 'goatcounter'

# Prefer color scheme setting.
# Để trống để theo hệ thống, hoặc 'light' | 'dark'
theme_mode: dark

# CDN endpoint for media resources (để trống nếu không dùng)
cdn: ""

# Avatar (đã giữ đường dẫn bạn cung cấp)
avatar: "https://media.licdn.com/dms/image/v2/D4E03AQG1Nv6NgDJaEw/profile-displayphoto-crop_800_800/B4EZku_7AEGcAI-/0/1757430136451?e=1760572800&v=beta&t=zNLw3E8mrK6X-D0n8s1HOyAUsL3Ogb-Tt7wjOCCnIjU"

# Social preview image (ghi đường dẫn nếu muốn custom og:image)
social_preview_image: ""

# Table of Contents in posts
toc: true

# Comments: bật Giscus (ví dụ). Nếu không dùng comment, để provider: ""
comments:
  provider: giscus
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo: "pzhat/your-comments-repo"    # <-- thay bằng <gh-username>/<repo> thực tế
    repo_id: ""                         # <-- lấy từ giscus admin
    category: "General"                 # <-- tên category trong repo issues
    category_id: ""                     # <-- lấy từ giscus admin
    mapping: "pathname"
    strict: "0"
    input_position: "bottom"
    lang: "en"
    reactions_enabled: 1

# Self-hosted static assets (mặc định tắt)
assets:
  self_host:
    enabled: false
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

# Base URL (để trống nếu host trên username.github.io)
baseurl: ""

# kramdown & other recommended defaults (không thay đổi nhiều)
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/